[project]
org-name = "ldclakmal"
version = "1.0.2"
authors = ["Chanaka Lakmal"]
keywords= ["sample", "extension", "quickstart"]
repository= "https://github.com/ldclakmal/ballerina-extension-quickstart"
license = ["Apache-2.0"]

[dependencies]

[platform]
target = "java8"

    [[platform.libraries]]
    module = "sample"
    path = "./sample/target/sample-module-1.0.0.jar"
    artifactId = "sample"
    version = "1.0.0"
    groupId = "lk.avix"