name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build Extension
    runs-on: ubuntu-latest
    env:
      BALLERINA_VERSION: ${{ secrets.BALLERINA_VERSION }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Ballerina
        run: wget https://dist.ballerina.io/downloads/${{ env.BALLERINA_VERSION }}/ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
      - name: Install Ballerina
        run: |
          sudo dpkg -i ballerina-linux-installer-x64-${{ env.BALLERINA_VERSION }}.deb
          sudo apt-get install -f
          bal -v
      - name: Build with Gradle
        env:
          packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
          packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
        run: |
          ./gradlew publish
      - name: Archive Error Log
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Ballerina Internal Log
          path: extension-ballerina/ballerina-internal.log
          if-no-files-found: ignore
